Move parameter and schema files
opengeospatial/ogcapi-environmental-data-retrieval pull request #389
Opened 2022-06-30 15:21 UTC by m-burgoyne

Move the parameter and schema yaml files back into the old folder structure

2022-07-01 11:04 UTC, ghobona commented
The following files from v1.0.0 are missing. I suggest returning them into the schemas folder, even if they are not used by v1.0.1:

* schemas/compositeAxes.yaml
* schemas/dataQuery.yaml
* schemas/groups.yaml
* schemas/parameterExtent.yaml
* parameters/cubeCoords.yaml
* parameters/groupId.yaml
 
I also suggest adding a README.txt file that explains that the files listed above have been included but are intentionally not used from v1.0.1 onwards.

2022-07-01 11:41 UTC, ghobona requested changes
The following files from v1.0.0 are missing. I suggest returning them into the schemas and parameters folder, even if they are not used by v1.0.1:

* [schemas/compositeAxes.yaml](https://schemas.opengis.net/ogcapi/edr/1.0/openapi/schemas/compositeAxes.yaml)
* [schemas/dataQuery.yaml](https://schemas.opengis.net/ogcapi/edr/1.0/openapi/schemas/dataQuery.yaml)
* [schemas/groups.yaml](https://schemas.opengis.net/ogcapi/edr/1.0/openapi/schemas/groups.yaml)
* [schemas/parameterExtent.yaml](https://schemas.opengis.net/ogcapi/edr/1.0/openapi/schemas/groups.yaml)
* [parameters/cubeCoords.yaml](https://schemas.opengis.net/ogcapi/edr/1.0/openapi/parameters/cubeCoords.yaml)
* [parameters/groupId.yaml](https://schemas.opengis.net/ogcapi/edr/1.0/openapi/parameters/groupId.yaml)
 
I also suggest adding a README.txt file that explains that the files listed above have been included but are intentionally not used from v1.0.1 onwards.

2022-07-08 13:07 UTC, ghobona approved these changes

2022-07-15 22:41 UTC, tomkralidis approved these changes

2022-07-21 10:13 UTC, ghobona commented
Merging the Pull Request because it has been approved.

2022-07-21 10:13 UTC, merged